namespace CupCake.Utils.Blocks
{
    public enum Block
    {
        BlockGravityNothing = 0,
        BlockGravityLeft = 1,
        BlockGravityUp = 2,
        BlockGravityRight = 3,
        BlockGravityDot = 4,

        BlockCrown = 5,

        BlockKeyRed = 6,
        BlockKeyGreen = 7,
        BlockKeyBlue = 8,

        BlockBasicGrey = 9,
        BlockBasicDarkBlue = 10,
        BlockBasicPurple = 11,
        BlockBasicRed = 12,
        BlockBasicYellow = 13,
        BlockBasicGreen = 14,
        BlockBasicLightBlue = 15,
        BlockBasicBlack = 182,
        BackgroundBasicGrey = 500,
        BackgroundBasicDarkBlue = 501,
        BackgroundBasicPurple = 502,
        BackgroundBasicRed = 503,
        BackgroundBasicYellow = 504,
        BackgroundBasicGreen = 505,
        BackgroundBasicLightBlue = 506,

        BlockBrickSaturatedBrown = 16,
        BlockBrickDarkGreen = 17,
        BlockBrickPurple = 18,
        BlockBrickLightGreen = 19,
        BlockBrickRed = 20,
        BlockBrickPaleBrown = 21,
        BackgroundBrickSaturatedBrown = 507,
        BackgroundBrickDarkGreen = 508,
        BackgroundBrickPurple = 509,
        BackgroundBrickLightGreen = 510,
        BackgroundBrickRed = 511,
        BackgroundBrickPaleBrown = 512,

        BlockSpecial1 = 22,
        BlockSpecial2 = 32,
        BlockSpecialNormalBlack = 33,
        BlockSpecialFullyBlack = 44,

        BlockDoorRed = 23,
        BlockDoorGreen = 24,
        BlockDoorBlue = 25,
        BlockDoorCoinDoor = 43,
        BlockDoorTimedDoor = 156,
        BlockDoorPurpleSwitchable = 184,
        BlockDoorBuildersClub = 200,
        BlockDoorZombie = 207,

        BlockGateRed = 26,
        BlockGateGreen = 27,
        BlockGateBlue = 28,
        BlockGateTimedGate = 157,
        BlockGateCoinGate = 165,
        BlockGatePurpleSwitchable = 185,
        BlockGateBuildersClub = 201,
        BlockGateZombie = 206,

        BlockMetalWhite = 29,
        BlockMetalRed = 30,
        BlockMetalYellow = 31,

        BlockGrass1 = 34,
        BlockGrass2 = 35,
        BlockGrass3 = 36,

        BlockBetaPink = 37,
        BlockBetaGreen = 38,
        BlockBetaBlue = 39,
        BlockBetaRed = 40,
        BlockBetaYellow = 41,
        BlockBetaGrey = 42,

        BlockFactory1 = 45,
        BlockFactory2 = 46,
        BlockFactory3 = 47,
        BlockFactory4 = 48,
        BlockFactory5 = 49,

        BlockSecretUnpassable = 50,
        BlockSecretPassable = 243,

        BlockGlassRed = 51,
        BlockGlassPink = 52,
        BlockGlassPurple = 53,
        BlockGlassDarkBlue = 54,
        BlockGlassLightBlue = 55,
        BlockGlassGreen = 56,
        BlockGlassYellow = 57,
        BlockGlassOrange = 58,

        BlockSummer2011Sand = 59,
        DecorationSummer2011Sunshade = 228,
        DecorationSummer20111 = 229,
        DecorationSummer20112 = 230,
        DecorationSummer2011Rock = 231,

        BlockCandySolidPink = 60,
        BlockCandyOneWayPink = 61,
        BlockCandyOneWayRed = 62,
        BlockCandyOneWayBlue = 63,
        BlockCandyOneWayGreen = 64,
        BlockCandySolidStripeyRedWhite = 65,
        BlockCandySolidStripeyYellowBlackPink = 66,
        BlockCandySolidChocolate = 67,
        DecorationCandy = 227,
        BackgroundCandyPink = 539,
        BackgroundCandyBlue = 540,

        BlockHalloween20111 = 68,
        BlockHalloween20112 = 69,
        DecorationHalloween2011GraveStone = 224,
        DecorationHalloween20112 = 225,
        DecorationHalloween20113 = 226,
        BackgroundHalloween20111 = 541,
        BackgroundHalloween20112 = 542,
        BackgroundHalloween20113 = 543,
        BackgroundHalloween20114 = 544,

        BlockMineralRed = 70,
        BlockMineralPink = 71,
        BlockMineralDarkBlue = 72,
        BlockMineralLightBlue = 73,
        BlockMineralGreen = 74,
        BlockMineralYellow = 75,
        BlockMineralOrange = 76,

        BlockMusicPiano = 77,
        BlockMusicDrum = 83,

        BlockChristmas2011YellowBox = 78,
        BlockChristmas2011WhiteBox = 79,
        BlockChristmas2011RedBox = 80,
        BlockChristmas2011BlueBox = 81,
        BlockChristmas2011GreenBox = 82,
        DecorationChristmas2011Star = 218,
        DecorationChristmas2011Wreath = 219,
        DecorationChristmas2011SphereBlue = 220,
        DecorationChristmas2011SphereGreen = 221,
        DecorationChristmas2011SphereRed = 222,

        BlockSciFiSolidRed = 84,
        BlockSciFiSolidBlue = 85,
        BlockSciFiSolidGrey = 86,
        BlockSciFiSolidWhite = 87,
        BlockSciFiSolidBrown = 88,
        BlockSciFiOneWayRed = 89,
        BlockSciFiOneWayBlue = 90,
        BlockSciFiOneWayGreen = 91,

        BlockPrison = 92,
        DecorationPrison = 261,
        BackgroundPrisonBrickWall = 550,
        BackgroundPrisonPicture = 551,
        BackgroundPrisonWindowBlue = 552,
        BackgroundPrisonWindowBlack = 553,

        BlockPirate1 = 93,
        BlockPirateChest = 94,
        DecorationPirate1 = 271,
        DecorationPirateSkull = 272,
        BackgroundPirate1 = 554,
        BackgroundPirate2 = 555,
        BackgroundPirate3 = 556,
        BackgroundPirate4 = 557,
        BackgroundPirate5 = 558,
        BackgroundPirate6 = 559,
        BackgroundPirateSkull = 560,

        BlockViking = 95,
        DecorationVikingRedShield = 273,
        DecorationVikingBlueShield = 274,
        DecorationVikingAx = 275,
        BackgroundViking1 = 561,
        BackgroundViking2 = 562,
        BackgroundViking3 = 563,

        BlockNinjaWhite = 96,
        BlockNinjaGrey = 97,
        DecorationNinja1 = 276,
        DecorationNinja2 = 277,
        DecorationNinja3 = 278,
        DecorationNinja4 = 279,
        DecorationNinja5 = 280,
        DecorationNinja6 = 281,
        DecorationNinja7 = 282,
        DecorationNinja8 = 283,
        DecorationNinja9 = 284,
        BackgroundNinjaWhiteWall = 564,
        BackgroundNinjaGreyWall = 565,
        BackgroundNinjaLitWindow = 566,
        BackgroundNinjaDarkWindow = 567,

        BlockCoinGold = 100,
        BlockCoinBlue = 101,

        BlockSwitchPurple = 113,

        BlockBoostLeft = 114,
        BlockBoostRight = 115,
        BlockBoostUp = 116,
        BlockBoostDown = 117,

        BlockLadderCastle = 118,
        BlockLadderNinja = 120,
        BlockLadderJungleVertical = 98,
        BlockLadderJungleHorizontal = 99,

        BlockWater = 119,
        DecorationWater = 300,
        BackgroundWaterBasic = 574,
        BackgroundWaterOctopus = 575,
        BackgroundWaterFish = 576,
        BackgroundWaterSeaHorse = 577,
        BackgroundWaterSeaweed = 578,

        BlockToolWinTrophy = 121,
        BlockToolSpawnPoint = 255,
        BlockToolCheckpoint = 360,

        BlockCowboyBrownLit = 122,
        BlockCowboyRedLit = 123,
        BlockCowboyBlueLit = 124,
        BlockCowboyBrownDark = 125,
        BlockCowboyRedDark = 126,
        BlockCowboyBlueDark = 127,
        DecorationCowboyPoleLit = 285,
        DecorationCowboyPoleDark = 286,
        DecorationCowboyDoorBrownLeft = 287,
        DecorationCowboyDoorBrownRight = 288,
        DecorationCowboyDoorRedLeft = 289,
        DecorationCowboyDoorRedRight = 290,
        DecorationCowboyDoorBlueLeft = 291,
        DecorationCowboyDoorBlueRight = 292,
        DecorationCowboyWindow = 293,
        DecorationCowboyTableBrownLit = 294,
        DecorationCowboyTableBrownDark = 295,
        DecorationCowboyTableRedLit = 296,
        DecorationCowboyTableRedDark = 297,
        DecorationCowboyTableBlueLit = 298,
        DecorationCowboyTableBlueDark = 299,
        BackgroundCowboyBrownLit = 568,
        BackgroundCowboyBrownDark = 569,
        BackgroundCowboyRedLit = 570,
        BackgroundCowboyRedDark = 571,
        BackgroundCowboyBlueLit = 572,
        BackgroundCowboyBlueDark = 573,

        BlockPlasticLightGreen = 128,
        BlockPlasticRed = 129,
        BlockPlasticYellow = 130,
        BlockPlasticLightBlue = 131,
        BlockPlasticDarkBlue = 132,
        BlockPlasticPink = 133,
        BlockPlasticDarkGreen = 134,
        BlockPlasticOrange = 135,

        BlockSandLightYellow = 137,
        BlockSandGrey = 138,
        BlockSandDarkerYellow = 139,
        BlockSandOrange = 140,
        BlockSandLightBrown = 141,
        BlockSandDarkBrown = 142,
        DecorationSandLightYellow = 301,
        DecorationSandGrey = 302,
        DecorationSandDarkerYellow = 303,
        DecorationSandOrange = 304,
        DecorationSandLightBrown = 305,
        DecorationSandDarkBrown = 306,
        BackgroundSandLightYellow = 579,
        BackgroundSandGrey = 580,
        BackgroundSandDarkerYellow = 581,
        BackgroundSandOrange = 582,
        BackgroundSandLightBrown = 583,
        BackgroundSandDarkBrown = 584,

        BlockCloud = 143,
        DecorationCloud1 = 311,
        DecorationCloud2 = 312,
        DecorationCloud3 = 313,
        DecorationCloud4 = 314,
        DecorationCloud5 = 315,
        DecorationCloud6 = 316,
        DecorationCloud7 = 317,
        DecorationCloud8 = 318,

        BlockPlateIron1 = 144,
        BlockPlateIron2 = 145,

        BlockIndustrialOneWay = 146,
        BlockIndustrial2 = 147,
        BlockIndustrial3 = 148,
        BlockIndustrial4 = 149,
        BlockIndustrialConveyorBelt1 = 150,
        BlockIndustrialConveyorBelt2 = 151,
        BlockIndustrialConveyorBelt3 = 152,
        BlockIndustrialConveyorBelt4 = 153,
        BackgroundIndustrialNoPlate = 585,
        BackgroundIndustrialGreyPlate = 586,
        BackgroundIndustrialBluePlate = 587,
        BackgroundIndustrialGreenPlate = 588,
        BackgroundIndustrialYellowPlate = 589,

        BlockTimbered = 154,
        BackgroundTimberedHouseTopHay = 590,
        BackgroundTimberedHouseTopRed = 591,
        BackgroundTimberedHouseTopGrey = 592,
        BackgroundTimbered4 = 593,
        BackgroundTimbered5 = 594,
        BackgroundTimbered6 = 595,
        BackgroundTimbered7 = 596,
        BackgroundTimbered8 = 597,
        BackgroundTimbered9 = 598,

        BlockCastleOneWay = 158,
        BlockCastleWall = 159,
        BlockCastleWindow = 160,
        DecorationCastle1 = 325,
        DecorationCastle2 = 326,
        BackgroundCastle = 599,

        BlockMedievalAnvil = 162,
        BlockMedievalBarrel = 163,
        DecorationMedievalBlueBanner = 327,
        DecorationMedievalRedBanner = 328,
        DecorationMedievalSword = 329,
        DecorationMedievalShield = 330,
        DecorationMedievalRock = 331,
        BackgroundMedieval = 600,

        BlockPipeHoleOnLeft = 166,
        BlockPipeHorizontalMiddle = 167,
        BlockPipeHoleOnRight = 168,
        BlockPipeHoleOnUp = 169,
        BlockPipeVerticalMiddle = 170,
        BlockPipeHoleOnDown = 171,

        BlockRocketWhite = 172,
        BlockRocketBlue = 173,
        BlockRocketGreen = 174,
        BlockRocketRed = 175,
        DecorationRocketGreenSign = 332,
        DecorationRocketRed = 333,
        DecorationRocketBlue = 334,
        DecorationRocketComputer = 335,
        BackgroundRocketWhite = 601,
        BackgroundRocketBlue = 602,
        BackgroundRocketGreen = 603,
        BackgroundRocketRed = 604,

        BlockMars1 = 176,
        BlockMars2 = 177,
        BlockMars3 = 178,
        BlockMars4 = 179,
        BlockMars5 = 180,
        BlockMars6 = 181,
        DecorationMars = 336,
        BackgroundMarsNoStars = 605,
        BackgroundMarsSmallStar = 606,
        BackgroundMarsBigStar = 607,

        BlockCheckeredGrey = 186,
        BlockCheckeredDarkBlue = 187,
        BlockCheckeredPurple = 188,
        BlockCheckeredRed = 189,
        BlockCheckeredYellow = 190,
        BlockCheckeredGreen = 191,
        BlockCheckeredLightBlue = 192,

        BlockJungleRuinsSolidRoundedEdgeFace = 193,
        BlockJungleRuinsOneWay = 194,
        BlockJungleRuinsSolidNonRoundedGrey = 195,
        BlockJungleRuinsSolidRed = 196,
        BlockJungleRuinsSolidBlue = 197,
        BlockJungleRuinsSolidYellow = 198,

        BlockJungleVase = 199,

        BlockLavaYellow = 202,
        BlockLavaOrange = 203,
        BlockLavaRed = 204,
        BackgroundLavaYellow = 627,
        BackgroundLavaOrange = 628,
        BackgroundLavaRed = 629,

        BlockSpartaSolidGrey = 208,
        BlockSpartaSolidGreen = 209,
        BlockSpartaSolidRed = 210,
        BlockSpartaOneWay = 211,
        DecorationSpartaPillarTop = 382,
        DecorationSpartaPillarMiddle = 383,
        DecorationSpartaPillarBottom = 384,
        BackgroundSpartaGrey = 638,
        BackgroundSpartaGreen = 639,
        BackgroundSpartaRed = 640,

        BlockFarm = 212,
        DecorationFarmCrop = 386,
        DecorationFarmPlants = 387,
        DecorationFarmFenceLeftEnded = 388,
        DecorationFarmFenceRightEnded = 389,

        DecorationPrizeTrophy = 223,

        DecorationSpring2011Grass1 = 233,
        DecorationSpring2011Grass2 = 234,
        DecorationSpring2011Grass3 = 235,
        DecorationSpring2011OblongBush1 = 236,
        DecorationSpring2011OblongBush2 = 237,
        DecorationSpring2011OblongBush3 = 238,
        DecorationSpring2011Flower = 239,
        DecorationSpring2011GlobularBush = 240,

        BlockDiamond = 241,

        BlockPortal = 242,
        BlockWorldPortal = 374,
        BlockInvisiblePortal = 381,

        DecorationNewYear2010Purple = 244,
        DecorationNewYear2010Yellow = 245,
        DecorationNewYear2010Blue = 246,
        DecorationNewYear2010Red = 247,
        DecorationNewYear2010Green = 248,

        DecorationChristmas20101 = 249,
        DecorationChristmas20102 = 250,
        DecorationChristmas2010SnowFreeTree = 251,
        DecorationChristmas2010SnowyTree = 252,
        DecorationChristmas2010SnowyFence = 253,
        DecorationChristmas2010SnowFreeFence = 254,

        DecorationEaster2012BlueEgg = 256,
        DecorationEaster2012PinkEgg = 257,
        DecorationEaster2012YellowEgg = 258,
        DecorationEaster2012RedEgg = 259,
        DecorationEaster2012GreenEgg = 260,

        DecorationWindowFullyTransparent = 262,
        DecorationWindowTransparentLightGreen = 263,
        DecorationWindowTransparentDarkGreen = 264,
        DecorationWindowTransparentLightBlue = 265,
        DecorationWindowTransparentDarkBlue = 266,
        DecorationWindowTransparentPink = 267,
        DecorationWindowTransparentRed = 268,
        DecorationWindowTransparentOrange = 269,
        DecorationWindowTransparentYellow = 270,

        DecorationSummer2012Ball = 307,
        DecorationSummer2012Bucket = 308,
        DecorationSummer2012Grubber = 309,
        DecorationSummer2012Cocktail = 310,

        DecorationWarningSignFire = 319,
        DecorationWarningSignSkull = 320,
        DecorationWarningSignLightning = 321,
        DecorationWarningSignCross = 322,
        DecorationWarningSignHorizontalLine = 323,
        DecorationWarningSignVerticalLine = 324,

        BlockCake = 337,

        DecorationMonsterRockGroundBig = 338,
        DecorationMonsterRockGroundSmall = 339,
        DecorationMonsterRockCeiling = 340,
        DecorationMonsterEyeOrange = 341,
        DecorationMonsterEyeBlue = 342,
        BackgroundMonsterNormal = 608,
        BackgroundMonsterDark = 609,

        DecorationFogFilled = 343,
        DecorationFog2 = 344,
        DecorationFog3 = 345,
        DecorationFog4 = 346,
        DecorationFog5 = 347,
        DecorationFog6 = 348,
        DecorationFog7 = 349,
        DecorationFog8 = 350,
        DecorationFog9 = 351,

        DecorationHalloween20121 = 352,
        DecorationHalloween20122 = 353,
        DecorationHalloween2012WiresVertical = 354,
        DecorationHalloween2012WiresHorizontal = 355,
        DecorationHalloween20125 = 356,

        DecorationJungleGrass = 357,
        DecorationJungle2 = 358,
        DecorationJungleTrophy = 359,

        BlockHazardSpike = 361,
        BlockHazardFire = 368,

        BlockSwamp = 369,
        DecorationSwamp1 = 370,
        DecorationSwamp2 = 371,
        DecorationSwamp3 = 372,
        DecorationSwamp4 = 373,
        BackgroundSwamp = 630,

        DecorationChristmas2012BlueVertical = 362,
        DecorationChristmas2012BlueHorizontal = 363,
        DecorationChristmas2012BlueCross = 364,
        DecorationChristmas2012RedVertical = 365,
        DecorationChristmas2012RedHorizontal = 366,
        DecorationChristmas2012RedCross = 367,

        DecorationSciFi2013BlueSlope = 375,
        DecorationSciFi2013BlueStraight = 376,
        DecorationSciFi2013YellowSlope = 377,
        DecorationSciFi2013YellowStraight = 378,
        DecorationSciFi2013GreenSlope = 379,
        DecorationSciFi2013GreenStraight = 380,
        BackgroundSciFi2013 = 637,

        DecorationSign = 385,

        BackgroundCheckeredGrey = 513,
        BackgroundCheckeredDarkBlue = 514,
        BackgroundCheckeredPurple = 515,
        BackgroundCheckeredRed = 516,
        BackgroundCheckeredYellow = 517,
        BackgroundCheckeredGreen = 518,
        BackgroundCheckeredLightBlue = 519,

        BackgroundDarkGrey = 520,
        BackgroundDarkDarkBlue = 521,
        BackgroundDarkPurple = 522,
        BackgroundDarkRed = 523,
        BackgroundDarkYellow = 524,
        BackgroundDarkGreen = 525,
        BackgroundDarkLightBlue = 526,

        BackgroundPastelYellow = 527,
        BackgroundPastelDarkerGreen = 528,
        BackgroundPastelLimeGreen = 529,
        BackgroundPastelLightBlue = 530,
        BackgroundPastelDarkerBlue = 531,
        BackgroundPastelRed = 532,

        BackgroundCanvasSaturatedBrown = 533,
        BackgroundCanvasPaleBrown = 534,
        BackgroundCanvasYellow = 535,
        BackgroundCanvasGreen = 536,
        BackgroundCanvasBlue = 537,
        BackgroundCanvasGrey = 538,

        BackgroundCarnivalStripeyRedYellow = 545,
        BackgroundCarnivalStripeyPurpleBlue = 546,
        BackgroundCarnivalPink = 547,
        BackgroundCarnivalChecker = 548,
        BackgroundCarnivalGreen = 549,

        BackgroundNormalGrey = 610,
        BackgroundNormalDarkBlue = 611,
        BackgroundNormalPurple = 612,
        BackgroundNormalRed = 613,
        BackgroundNormalYellow = 614,
        BackgroundNormalGreen = 615,
        BackgroundNormalLightBlue = 616,

        BackgroundJungleRuinsGrey = 617,
        BackgroundJungleRuinsRed = 618,
        BackgroundJungleRuinsBlue = 619,
        BackgroundJungleRuinsYellow = 620,

        BackgroundJungleLight = 621,
        BackgroundJungleNormal = 622,
        BackgroundJungleDark = 623,

        BackgroundChristmas2012Yellow = 624,
        BackgroundChristmas2012Green = 625,
        BackgroundChristmas2012Blue = 626,

        DecorationLabel = 1000
    }
}